export const Errors: Error[] = [
  {name: 'required', message: 'Το πεδίο είναι υποχρεωτικό'},
  {name: 'email', message: 'Πρέπει να δοθεί ένα έγκυρο email'},
  {name: 'pattern', message: ''},
  {name: 'maxlength', message: ''},
  {name: 'minlength', message: ''},
  {name: 'passwordMismatch', message: 'Πρέπει να δοθεί το ίδιο συνθηματικό με το παραπάνω'},
  {name: 'usernameExists', message: 'To email υπάρχει ήδη καταχωρημένο'},
  {name: 'recordNumberExists', message: 'Ο Αριθμός Μητρώου υπάρχει ήδη καταχωρημένος'},
  {name: 'languageCodeExists', message: 'Ο Κωδικός Γλώσσας υπάρχει ήδη καταχωρημένος'},
  {name: 'languageNameExists', message: 'Η Γλώσσα υπάρχει ήδη καταχωρημένη'},
  {name: 'regionNameExists', message: 'Η Περιοχή υπάρχει ήδη καταχωρημένη'},
  {name: 'categoryNameExists', message: 'Η Κατηγορία υπάρχει ήδη καταχωρημένη'},
]

export const BackendErrors: Error[] = [
  {name: 'expiredToken', message: 'Αποτυχία στην αυθεντικοποίηση'},
  {name: 'invalidToken', message: 'Αποτυχία στην αυθεντικοποίηση'},
  {name: 'UserNotAuthenticated', message: 'Πρέπει να συνδεθείτε για να πραγματοποιήσετε αυτή την ενέργεια'},
  {name: 'UserNotAuthorized', message: 'Δεν έχετε δικαιώματα για αυτή την ενέργεια'},
  {name: 'UserAlreadyExists', message: 'To email υπάρχει ήδη καταχωρημένο'},
  {name: 'UserNotFound', message: 'Ο χρήστης δε βρέθηκε'},
  {name: 'GuideAlreadyExists', message: 'Ο Αριθμός Μητρώου υπάρχει ήδη καταχωρημένος'},
  {name: 'GuideNotFound', message: 'Ο λογαριασμός δε βρέθηκε'},
  {name: 'GuideInvalidArgument', message: 'Ο λογαριασμός είναι απενεργοποιημένος'},
  {name: 'VisitorNotFound', message: 'Ο λογαριασμός δε βρέθηκε'},
  {name: 'VisitorInvalidArgument', message: 'Ο λογαριασμός είναι απενεργοποιημένος'},
  {name: 'ActivityNotFound', message: 'Η δραστηριότητα δε βρέθηκε'},
  {name: 'CategoryAlreadyExists', message: 'Η κατηγορία υπάρχει ήδη'},
  {name: 'CategoryNotFound', message: 'Η κατηγορία δε βρέθηκε'},
  {name: 'CategoryInvalidArgument', message: 'Η κατηγορία δεν είναι έγκυρη'},
  {name: 'LanguageAlreadyExists', message: 'Η γλώσσα υπάρχει ήδη'},
  {name: 'LanguageNotFound', message: 'Η γλώσσα δε βρέθηκε'},
  {name: 'LanguageInvalidArgument', message: 'Η γλώσσα δεν είναι έγκυρη'},
  {name: 'RegionAlreadyExists', message: 'Η περιοχή υπάρχει ήδη'},
  {name: 'RegionNotFound', message: 'Η περιοχή δε βρέθηκε'},
  {name: 'RegionInvalidArgument', message: 'Η περιοχή δεν είναι έγκυρη'},
]
